# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\"\x11\n\x0fGetPriceRequest\"!\n\x10GetPriceResponse\x12\r\n\x05price\x18\x01 \x01(\t\"\x1f\n\x0bSellRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"\x1e\n\x0cSellResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"2\n\x0bResponseEnd\x12\x0f\n\x07revenue\x18\x01 \x01(\x05\x12\x12\n\npendencies\x18\x02 \x01(\x05\x32\x80\x01\n\x05Store\x12\x31\n\x08GetPrice\x12\x10.GetPriceRequest\x1a\x11.GetPriceResponse\"\x00\x12%\n\x04Sell\x12\x0c.SellRequest\x1a\r.SellResponse\"\x00\x12\x1d\n\x03\x45nd\x12\x06.Empty\x1a\x0c.ResponseEnd\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRICEREQUEST']._serialized_start=15
  _globals['_GETPRICEREQUEST']._serialized_end=32
  _globals['_GETPRICERESPONSE']._serialized_start=34
  _globals['_GETPRICERESPONSE']._serialized_end=67
  _globals['_SELLREQUEST']._serialized_start=69
  _globals['_SELLREQUEST']._serialized_end=100
  _globals['_SELLRESPONSE']._serialized_start=102
  _globals['_SELLRESPONSE']._serialized_end=132
  _globals['_EMPTY']._serialized_start=134
  _globals['_EMPTY']._serialized_end=141
  _globals['_RESPONSEEND']._serialized_start=143
  _globals['_RESPONSEEND']._serialized_end=193
  _globals['_STORE']._serialized_start=196
  _globals['_STORE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
