# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\"$\n\x0e\x42\x61lanceRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"\"\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\"6\n\x11SalesOrderRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"6\n\x12SalesOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08order_id\x18\x02 \x01(\x05\"F\n\x0fTransferRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x12\n\naccount_id\x18\x03 \x01(\t\"\"\n\x10TransferResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x0c\n\nEndRequest\"!\n\x0b\x45ndResponse\x12\x12\n\npendencies\x18\x01 \x01(\x05\x32\xc8\x01\n\x06Wallet\x12.\n\x07\x42\x61lance\x12\x0f.BalanceRequest\x1a\x10.BalanceResponse\"\x00\x12\x37\n\nSalesOrder\x12\x12.SalesOrderRequest\x1a\x13.SalesOrderResponse\"\x00\x12\x31\n\x08Transfer\x12\x10.TransferRequest\x1a\x11.TransferResponse\"\x00\x12\"\n\x03\x45nd\x12\x0b.EndRequest\x1a\x0c.EndResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BALANCEREQUEST']._serialized_start=16
  _globals['_BALANCEREQUEST']._serialized_end=52
  _globals['_BALANCERESPONSE']._serialized_start=54
  _globals['_BALANCERESPONSE']._serialized_end=88
  _globals['_SALESORDERREQUEST']._serialized_start=90
  _globals['_SALESORDERREQUEST']._serialized_end=144
  _globals['_SALESORDERRESPONSE']._serialized_start=146
  _globals['_SALESORDERRESPONSE']._serialized_end=200
  _globals['_TRANSFERREQUEST']._serialized_start=202
  _globals['_TRANSFERREQUEST']._serialized_end=272
  _globals['_TRANSFERRESPONSE']._serialized_start=274
  _globals['_TRANSFERRESPONSE']._serialized_end=308
  _globals['_ENDREQUEST']._serialized_start=310
  _globals['_ENDREQUEST']._serialized_end=322
  _globals['_ENDRESPONSE']._serialized_start=324
  _globals['_ENDRESPONSE']._serialized_end=357
  _globals['_WALLET']._serialized_start=360
  _globals['_WALLET']._serialized_end=560
# @@protoc_insertion_point(module_scope)
