# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import services_pb2 as proto_dot_services__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class WalletStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/services.Wallet/GetBalance',
                request_serializer=proto_dot_services__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=proto_dot_services__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.CreateSalesOrder = channel.unary_unary(
                '/services.Wallet/CreateSalesOrder',
                request_serializer=proto_dot_services__pb2.CreateSalesOrderRequest.SerializeToString,
                response_deserializer=proto_dot_services__pb2.CreateSalesOrderResponse.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_unary(
                '/services.Wallet/Transfer',
                request_serializer=proto_dot_services__pb2.TransferRequest.SerializeToString,
                response_deserializer=proto_dot_services__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.EndWallet = channel.unary_unary(
                '/services.Wallet/EndWallet',
                request_serializer=proto_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_services__pb2.EndWalletResponse.FromString,
                _registered_method=True)


class WalletServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSalesOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=proto_dot_services__pb2.GetBalanceRequest.FromString,
                    response_serializer=proto_dot_services__pb2.GetBalanceResponse.SerializeToString,
            ),
            'CreateSalesOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSalesOrder,
                    request_deserializer=proto_dot_services__pb2.CreateSalesOrderRequest.FromString,
                    response_serializer=proto_dot_services__pb2.CreateSalesOrderResponse.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=proto_dot_services__pb2.TransferRequest.FromString,
                    response_serializer=proto_dot_services__pb2.TransferResponse.SerializeToString,
            ),
            'EndWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.EndWallet,
                    request_deserializer=proto_dot_services__pb2.Empty.FromString,
                    response_serializer=proto_dot_services__pb2.EndWalletResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.Wallet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.Wallet', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Wallet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Wallet/GetBalance',
            proto_dot_services__pb2.GetBalanceRequest.SerializeToString,
            proto_dot_services__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSalesOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Wallet/CreateSalesOrder',
            proto_dot_services__pb2.CreateSalesOrderRequest.SerializeToString,
            proto_dot_services__pb2.CreateSalesOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Wallet/Transfer',
            proto_dot_services__pb2.TransferRequest.SerializeToString,
            proto_dot_services__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Wallet/EndWallet',
            proto_dot_services__pb2.Empty.SerializeToString,
            proto_dot_services__pb2.EndWalletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrice = channel.unary_unary(
                '/services.Store/GetPrice',
                request_serializer=proto_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_services__pb2.GetPriceResponse.FromString,
                _registered_method=True)
        self.Sell = channel.unary_unary(
                '/services.Store/Sell',
                request_serializer=proto_dot_services__pb2.SellRequest.SerializeToString,
                response_deserializer=proto_dot_services__pb2.SellResponse.FromString,
                _registered_method=True)
        self.EndStore = channel.unary_unary(
                '/services.Store/EndStore',
                request_serializer=proto_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_services__pb2.EndStoreResponse.FromString,
                _registered_method=True)


class StoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrice,
                    request_deserializer=proto_dot_services__pb2.Empty.FromString,
                    response_serializer=proto_dot_services__pb2.GetPriceResponse.SerializeToString,
            ),
            'Sell': grpc.unary_unary_rpc_method_handler(
                    servicer.Sell,
                    request_deserializer=proto_dot_services__pb2.SellRequest.FromString,
                    response_serializer=proto_dot_services__pb2.SellResponse.SerializeToString,
            ),
            'EndStore': grpc.unary_unary_rpc_method_handler(
                    servicer.EndStore,
                    request_deserializer=proto_dot_services__pb2.Empty.FromString,
                    response_serializer=proto_dot_services__pb2.EndStoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.Store', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Store(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Store/GetPrice',
            proto_dot_services__pb2.Empty.SerializeToString,
            proto_dot_services__pb2.GetPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Store/Sell',
            proto_dot_services__pb2.SellRequest.SerializeToString,
            proto_dot_services__pb2.SellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.Store/EndStore',
            proto_dot_services__pb2.Empty.SerializeToString,
            proto_dot_services__pb2.EndStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
