# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/services.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/services.proto\x12\x08services\"\x07\n\x05\x45mpty\"\x1f\n\x11GetBalanceRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12GetBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"5\n\x17\x43reateSalesOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"<\n\x18\x43reateSalesOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08order_id\x18\x02 \x01(\x05\"K\n\x0fTransferRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x16\n\x0e\x64\x65st_wallet_id\x18\x03 \x01(\t\"\"\n\x10TransferResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\'\n\x11\x45ndWalletResponse\x12\x12\n\npendencies\x18\x01 \x01(\x05\"!\n\x10GetPriceResponse\x12\r\n\x05price\x18\x01 \x01(\x05\"\x1f\n\x0bSellRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"\x1e\n\x0cSellResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"C\n\x10\x45ndStoreResponse\x12\x0f\n\x07revenue\x18\x01 \x01(\x05\x12\x1e\n\x16wallet_server_response\x18\x02 \x01(\x05\x32\xb2\x02\n\x06Wallet\x12I\n\nGetBalance\x12\x1b.services.GetBalanceRequest\x1a\x1c.services.GetBalanceResponse\"\x00\x12[\n\x10\x43reateSalesOrder\x12!.services.CreateSalesOrderRequest\x1a\".services.CreateSalesOrderResponse\"\x00\x12\x43\n\x08Transfer\x12\x19.services.TransferRequest\x1a\x1a.services.TransferResponse\"\x00\x12;\n\tEndWallet\x12\x0f.services.Empty\x1a\x1b.services.EndWalletResponse\"\x00\x32\xb6\x01\n\x05Store\x12\x39\n\x08GetPrice\x12\x0f.services.Empty\x1a\x1a.services.GetPriceResponse\"\x00\x12\x37\n\x04Sell\x12\x15.services.SellRequest\x1a\x16.services.SellResponse\"\x00\x12\x39\n\x08\x45ndStore\x12\x0f.services.Empty\x1a\x1a.services.EndStoreResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_GETBALANCEREQUEST']._serialized_start=43
  _globals['_GETBALANCEREQUEST']._serialized_end=74
  _globals['_GETBALANCERESPONSE']._serialized_start=76
  _globals['_GETBALANCERESPONSE']._serialized_end=113
  _globals['_CREATESALESORDERREQUEST']._serialized_start=115
  _globals['_CREATESALESORDERREQUEST']._serialized_end=168
  _globals['_CREATESALESORDERRESPONSE']._serialized_start=170
  _globals['_CREATESALESORDERRESPONSE']._serialized_end=230
  _globals['_TRANSFERREQUEST']._serialized_start=232
  _globals['_TRANSFERREQUEST']._serialized_end=307
  _globals['_TRANSFERRESPONSE']._serialized_start=309
  _globals['_TRANSFERRESPONSE']._serialized_end=343
  _globals['_ENDWALLETRESPONSE']._serialized_start=345
  _globals['_ENDWALLETRESPONSE']._serialized_end=384
  _globals['_GETPRICERESPONSE']._serialized_start=386
  _globals['_GETPRICERESPONSE']._serialized_end=419
  _globals['_SELLREQUEST']._serialized_start=421
  _globals['_SELLREQUEST']._serialized_end=452
  _globals['_SELLRESPONSE']._serialized_start=454
  _globals['_SELLRESPONSE']._serialized_end=484
  _globals['_ENDSTORERESPONSE']._serialized_start=486
  _globals['_ENDSTORERESPONSE']._serialized_end=553
  _globals['_WALLET']._serialized_start=556
  _globals['_WALLET']._serialized_end=862
  _globals['_STORE']._serialized_start=865
  _globals['_STORE']._serialized_end=1047
# @@protoc_insertion_point(module_scope)
